---
- name: Copy MongoDB configuration
  tags: setup
  ansible.builtin.copy:
    src: mongod.conf
    dest: /root/mongod.conf
- name: Download dependencies
  tags: setup
  ansible.builtin.apt:
    name: "{{ mongodb_dependencies }}"
    state: present
- name: Download MongoDB
  tags: setup
  ansible.builtin.get_url:
    url: "{{ mongodb_download_url }}"
    dest: "{{ mongodb_download_dest }}"
    validate_certs: no
- name: Unpack MongoDB
  tags: setup
  ansible.builtin.unarchive:
    src: "{{ mongodb_download_dest }}"
    dest: /root/
    remote_src: true
- name: Copy MongoDB binaries to /usr/bin
  tags: setup
  ansible.builtin.copy:
    src: "{{ mongodb_binaries_src }}"
    dest: "{{ mongodb_binaries_dest }}"
    mode: 0755
    remote_src: true
- name: Create MongoDB data directory
  tags: setup
  ansible.builtin.file:
    path: "{{ mongodb_data_directory }}"
    state: directory
    mode: 0755
- name: Start MongoDB server
  tags: [never, start]
  ansible.builtin.command: mongod --config "{{ mongodb_config_file }}" --fork --logpath /var/log/mongodb.log
- name: Stop MongoDB server
  tags: [never, stop]
  ansible.builtin.command: mongod --config "{{ mongodb_config_file }}" --shutdown
